#!/bin/bash
source $(dirname "${BASH_SOURCE[0]}")/helper

docker build --pull --build-arg http_proxy="$http_proxy" --build-arg https_proxy="$https_proxy" $@ -t ${IMAGE} -f $(dirname "${BASH_SOURCE[0]}")/Dockerfile . 
