#!/bin/bash

#sv start register  || exit 1

source /etc/envvars
env

until curl http://$ETCD_HOST:4001/v2/keys/registry -s -S -w "%{http_code}" -o /dev/null | grep 200; do echo "waiting for ETCD to come online..."; sleep 3; done

exec 2>&1
exec confd -watch=true -interval 30 -backend=etcd -node "http://$ETCD_HOST:4001"
